# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-byte-track',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-byte-track',
                'lib_path': 'cjm_byte_track'},
  'syms': {'cjm_byte_track.core': {'cjm_byte_track.core.foo': ('core.html#foo', 'cjm_byte_track/core.py')}}}
